"""initial_schema

Revision ID: 33c55493ec25
Revises: 
Create Date: 2026-05-31 21:36:23.242882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33c55493ec25'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bangumi_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.Column('infobox_raw', sa.Text(), nullable=True),
    sa.Column('infobox_parsed', sa.JSON(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('comments_count', sa.Integer(), nullable=False),
    sa.Column('collects_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_characters_bangumi_id'), 'characters', ['bangumi_id'], unique=True)
    op.create_table('persons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bangumi_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('career', sa.JSON(), nullable=True),
    sa.Column('infobox_raw', sa.Text(), nullable=True),
    sa.Column('infobox_parsed', sa.JSON(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('comments_count', sa.Integer(), nullable=False),
    sa.Column('collects_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_persons_bangumi_id'), 'persons', ['bangumi_id'], unique=True)
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bangumi_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('name_cn', sa.String(length=500), nullable=True),
    sa.Column('name_en', sa.String(length=500), nullable=True),
    sa.Column('infobox_raw', sa.Text(), nullable=True),
    sa.Column('infobox_parsed', sa.JSON(), nullable=True),
    sa.Column('platform', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('nsfw', sa.Boolean(), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=True),
    sa.Column('series', sa.Boolean(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('meta_tags', sa.JSON(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('score_details', sa.JSON(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('wish_count', sa.Integer(), nullable=False),
    sa.Column('doing_count', sa.Integer(), nullable=False),
    sa.Column('done_count', sa.Integer(), nullable=False),
    sa.Column('on_hold_count', sa.Integer(), nullable=False),
    sa.Column('dropped_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subjects_bangumi_id'), 'subjects', ['bangumi_id'], unique=True)
    op.create_index(op.f('ix_subjects_date'), 'subjects', ['date'], unique=False)
    op.create_index(op.f('ix_subjects_name_cn'), 'subjects', ['name_cn'], unique=False)
    op.create_index(op.f('ix_subjects_score'), 'subjects', ['score'], unique=False)
    op.create_index(op.f('ix_subjects_type'), 'subjects', ['type'], unique=False)
    op.create_index('ix_subjects_type_date', 'subjects', ['type', 'date'], unique=False)
    op.create_index('ix_subjects_type_score', 'subjects', ['type', 'score'], unique=False)
    op.create_index(op.f('ix_subjects_updated_at'), 'subjects', ['updated_at'], unique=False)
    op.create_table('episodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bangumi_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('name_cn', sa.String(length=500), nullable=True),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('airdate', sa.String(length=20), nullable=True),
    sa.Column('disc', sa.Integer(), nullable=False),
    sa.Column('duration', sa.String(length=20), nullable=True),
    sa.Column('sort', sa.Float(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.bangumi_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_episodes_airdate'), 'episodes', ['airdate'], unique=False)
    op.create_index(op.f('ix_episodes_bangumi_id'), 'episodes', ['bangumi_id'], unique=True)
    op.create_index(op.f('ix_episodes_subject_id'), 'episodes', ['subject_id'], unique=False)
    op.create_table('person_characters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('summary', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.bangumi_id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.bangumi_id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.bangumi_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_characters_character_id'), 'person_characters', ['character_id'], unique=False)
    op.create_index(op.f('ix_person_characters_person_id'), 'person_characters', ['person_id'], unique=False)
    op.create_index(op.f('ix_person_characters_subject_id'), 'person_characters', ['subject_id'], unique=False)
    op.create_table('subject_characters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.bangumi_id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.bangumi_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subject_characters_character_id'), 'subject_characters', ['character_id'], unique=False)
    op.create_index(op.f('ix_subject_characters_subject_id'), 'subject_characters', ['subject_id'], unique=False)
    op.create_table('subject_persons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('appear_eps', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.bangumi_id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.bangumi_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subject_persons_person_id'), 'subject_persons', ['person_id'], unique=False)
    op.create_index(op.f('ix_subject_persons_subject_id'), 'subject_persons', ['subject_id'], unique=False)
    op.create_table('subject_relations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.Integer(), nullable=False),
    sa.Column('related_subject_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['related_subject_id'], ['subjects.bangumi_id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.bangumi_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sr_subject_related', 'subject_relations', ['subject_id', 'related_subject_id'], unique=False)
    op.create_index(op.f('ix_subject_relations_related_subject_id'), 'subject_relations', ['related_subject_id'], unique=False)
    op.create_index(op.f('ix_subject_relations_subject_id'), 'subject_relations', ['subject_id'], unique=False)
    op.create_table('user_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=2000), nullable=True),
    sa.Column('start_date', sa.String(length=20), nullable=True),
    sa.Column('finish_date', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.bangumi_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ur_user_status', 'user_records', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_user_records_status'), 'user_records', ['status'], unique=False)
    op.create_index(op.f('ix_user_records_subject_id'), 'user_records', ['subject_id'], unique=False)
    op.create_index(op.f('ix_user_records_user_id'), 'user_records', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_records_user_id'), table_name='user_records')
    op.drop_index(op.f('ix_user_records_subject_id'), table_name='user_records')
    op.drop_index(op.f('ix_user_records_status'), table_name='user_records')
    op.drop_index('ix_ur_user_status', table_name='user_records')
    op.drop_table('user_records')
    op.drop_index(op.f('ix_subject_relations_subject_id'), table_name='subject_relations')
    op.drop_index(op.f('ix_subject_relations_related_subject_id'), table_name='subject_relations')
    op.drop_index('ix_sr_subject_related', table_name='subject_relations')
    op.drop_table('subject_relations')
    op.drop_index(op.f('ix_subject_persons_subject_id'), table_name='subject_persons')
    op.drop_index(op.f('ix_subject_persons_person_id'), table_name='subject_persons')
    op.drop_table('subject_persons')
    op.drop_index(op.f('ix_subject_characters_subject_id'), table_name='subject_characters')
    op.drop_index(op.f('ix_subject_characters_character_id'), table_name='subject_characters')
    op.drop_table('subject_characters')
    op.drop_index(op.f('ix_person_characters_subject_id'), table_name='person_characters')
    op.drop_index(op.f('ix_person_characters_person_id'), table_name='person_characters')
    op.drop_index(op.f('ix_person_characters_character_id'), table_name='person_characters')
    op.drop_table('person_characters')
    op.drop_index(op.f('ix_episodes_subject_id'), table_name='episodes')
    op.drop_index(op.f('ix_episodes_bangumi_id'), table_name='episodes')
    op.drop_index(op.f('ix_episodes_airdate'), table_name='episodes')
    op.drop_table('episodes')
    op.drop_index(op.f('ix_subjects_updated_at'), table_name='subjects')
    op.drop_index('ix_subjects_type_score', table_name='subjects')
    op.drop_index('ix_subjects_type_date', table_name='subjects')
    op.drop_index(op.f('ix_subjects_type'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_score'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_name_cn'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_date'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_bangumi_id'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_persons_bangumi_id'), table_name='persons')
    op.drop_table('persons')
    op.drop_index(op.f('ix_characters_bangumi_id'), table_name='characters')
    op.drop_table('characters')
    # ### end Alembic commands ###
