"""add_person_relation

Revision ID: 512cd24e1346
Revises: 33c55493ec25
Create Date: 2026-05-31 21:55:53.644932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '512cd24e1346'
down_revision: Union[str, Sequence[str], None] = '33c55493ec25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person_relations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('person_type', sa.String(length=10), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('related_person_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.Integer(), nullable=False),
    sa.Column('spoiler', sa.Boolean(), nullable=False),
    sa.Column('ended', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_relations_person_id'), 'person_relations', ['person_id'], unique=False)
    op.create_index(op.f('ix_person_relations_related_person_id'), 'person_relations', ['related_person_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_person_relations_related_person_id'), table_name='person_relations')
    op.drop_index(op.f('ix_person_relations_person_id'), table_name='person_relations')
    op.drop_table('person_relations')
    # ### end Alembic commands ###
